paths:
  /api/products/:
    get:
      summary: Obtengo todos los productos.
      tags:
        - Productos
      responses:
        "200":
          description: Los productos se obtuvieron de forma correcta.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor.
    post:
      summary: Creamos un nuevo producto.
      tags:
        - Productos
      responses:
        "200":
          description: El carrito fue crado con exito.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor.
  /api/products/{pid}:
    get:
      summary: Recibo un producto en base a su ID (pid).
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: El "pid" es el id del producto que se quiere agregar al carrito.
          schema:
            $type: string
      responses:
        "200":
          description: El producto se obtuvo correctamente.
        "500":
          description: Error interno del servidor
    put:
      summary: Modificamos un producto en base a su ID (pid).
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: El pid es el id del producto que queremos modificar.
          schema:
            $type: string
      responses:
        "200":
          description: El producto se obtuvo correctamente.
        "500":
          description: Error interno del servidor
    delete:
      summary: Eliminamos un producto en base a su ID (pid).
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: El pid es el id del producto que queremos eliminar.
          schema:
            $type: string
      responses:
        "200":
          description: El producto se obtuvo correctamente.
        "500":
          description: Error interno del servidor

components:
  schemas:
    Products:
      type: object
      properties:
        title:
          type: String
          description: Título
        description:
          type: String
          description: Descripciónn
        price:
          type: Number
          description: Precio
        thumbnail:
          type: Number
          description: Imágenes de los productos.
        code:
          type: String
          description: Código del producto.
        stock:
          type: Number
          description: Cantidad de productos disponibles.
        category:
          type: String
          description: Categoría.
        owner:
          type: ObjectId
          description: Creador del producto.